version: "3.3"
services:
  pocketbase:
    image: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - data:/home/pocketbase/pb_data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:8090/_"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  home:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  data:
